# Generated by Django 3.2 on 2021-07-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveorders',
            old_name='rest_id',
            new_name='restaurant_id',
        ),
    ]
