# Generated by Django 3.2 on 2021-07-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_rest_id_saveorders_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveorders',
            name='total',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
